<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SUBMIT</name>
   <tag></tag>
   <elementGuidId>042661f1-dddc-4d39-b0e2-c9f2617d1125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61efb6e0-dc2f-4d62-a292-52d0da2ea455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>97de41a9-a576-456a-bcb6-ad67dbfef425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-2 font-frank-new text-xs max-w-[200px] border-2 py-2 dark:border-transparent w-full rounded-xl text-textWhite shadow-xl bg-gradient-to-t from-primaryLight via-primary bg-gradient-to-b to-primary hover:bg-gradient-to-t hover:to-primary hover:bg-gradient-to-b hover:from-primaryLight dark:bg-gradient-to-t dark:from-secondaryLight dark:via-secondary dark:bg-gradient-to-b dark:to-secondary dark:hover:bg-gradient-to-t dark:hover:to-secondary dark:via-secondary dark:hover:bg-gradient-to-b dark:hover:from-secondaryLight text-white w-40 block m-auto</value>
      <webElementGuid>bd4b9c63-7e32-428b-9c79-0b1666c213a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SUBMIT</value>
      <webElementGuid>6e675a35-23c8-4e02-9daa-09b4b6074a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;flex xxs:flex-col xs:flex-col sm:flex-col md:flex-row lg:flex-row xl:flex-row xxl:flex-row justify-center h-screen w-full&quot;]/div[@class=&quot;flex h-full xxs:full xs:w-full sm:full md:w-full lg:w-6/12 xl:w-6/12 xxl:w-6/12 align-center flex-col&quot;]/div[@class=&quot;flex justify-center self-center m-auto xxs:full xs:w-full sm:w-full md:w-10/12 lg:w-10/12 xl:w-10/12 xxl:w-10/12&quot;]/div[@class=&quot;prose self-center align-middle w-3/4&quot;]/form[1]/button[@class=&quot;p-2 font-frank-new text-xs max-w-[200px] border-2 py-2 dark:border-transparent w-full rounded-xl text-textWhite shadow-xl bg-gradient-to-t from-primaryLight via-primary bg-gradient-to-b to-primary hover:bg-gradient-to-t hover:to-primary hover:bg-gradient-to-b hover:from-primaryLight dark:bg-gradient-to-t dark:from-secondaryLight dark:via-secondary dark:bg-gradient-to-b dark:to-secondary dark:hover:bg-gradient-to-t dark:hover:to-secondary dark:via-secondary dark:hover:bg-gradient-to-b dark:hover:from-secondaryLight text-white w-40 block m-auto&quot;]</value>
      <webElementGuid>8b89fe7d-f0cc-462d-8b06-783c28be828a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>a231fb8e-543a-4e4f-9d52-d371d3850397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/form/button</value>
      <webElementGuid>0656587a-0d9b-419a-ae48-d25280c7cfd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password'])[1]/following::button[1]</value>
      <webElementGuid>a7a288ca-c2b4-428a-9673-72deb06cf198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>65329b90-6e1c-4d5e-980b-783895ed13d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login here'])[1]/preceding::button[1]</value>
      <webElementGuid>46aea337-0b34-418b-9373-3dd059d1d956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SUBMIT']/parent::*</value>
      <webElementGuid>d9d107a7-b018-43b7-8b79-7b23c9b80d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>09d47261-9e0f-4701-b50e-205b9d57a9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'SUBMIT' or . = 'SUBMIT')]</value>
      <webElementGuid>15e2747c-3866-4409-839b-b12ff5529af1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
