<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Full Name_name</name>
   <tag></tag>
   <elementGuidId>ae381784-fbb4-4ab4-a008-9908669db426</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fullName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fullName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53f489af-f3be-4682-82b5-9d9a13863942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Full Name</value>
      <webElementGuid>29908210-11de-47da-b2d7-4d5b8f7f5ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>05fab89a-5dac-466b-9cee-d1fb5d3c4fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fullName</value>
      <webElementGuid>51bb7915-2f20-4ebc-8007-207131f01f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-bgWhite h-10 border border-gray-300 text-gray-900 sm:text-sm rounded-xl focus:outline-none focus:border-primary dark:focus:border-secondary block w-full p-1.5 shadow-lg  dark:bg-dOnSurfaceBg dark:border-0 dark:text-dOnSurface dark:placeholder:text-textWhite</value>
      <webElementGuid>6f2980ac-f97d-477e-bef3-7db2eb54428f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullName&quot;)</value>
      <webElementGuid>39a13acd-2b75-4eee-8016-7a5bba324854</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fullName']</value>
      <webElementGuid>7c5b13e9-695e-43c2-a463-2bedd625f252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div[2]/div/form/div/div/input</value>
      <webElementGuid>678bc63e-f3a2-4409-888e-b00279fe363f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5a99e1b7-c3d7-4a7c-8d48-742e6f695fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Full Name' and @name = 'name' and @id = 'fullName']</value>
      <webElementGuid>31861a7a-2854-46dd-aba8-be398008311f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
