<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Find A Car</name>
   <tag></tag>
   <elementGuidId>ee0c229f-988a-476e-98ce-ef44094b6ccc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SimulateButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='SimulateButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ea8b722-17d0-407c-a225-ddc3210fec5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SimulateButton</value>
      <webElementGuid>108e4ca1-8e0b-4e97-94e4-1d3dac05d33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8a2f70d0-e3bb-49cb-9262-2737f0a0fc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-2 font-frank-new text-xs max-w-[200px] border-2 py-2 dark:border-transparent w-full rounded-xl text-textWhite shadow-xl bg-gradient-to-t from-primaryLight via-primary bg-gradient-to-b to-primary hover:bg-gradient-to-t hover:to-primary hover:bg-gradient-to-b hover:from-primaryLight dark:bg-gradient-to-t dark:from-secondaryLight dark:via-secondary dark:bg-gradient-to-b dark:to-secondary dark:hover:bg-gradient-to-t dark:hover:to-secondary dark:via-secondary dark:hover:bg-gradient-to-b dark:hover:from-secondaryLight text-white w-40 block m-auto text-center mt-4 uppercase</value>
      <webElementGuid>c23cbff0-9890-473f-98a0-abd8c2b73344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find A Car</value>
      <webElementGuid>8b2dfa73-5636-43b0-b9e3-88d2070c882b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SimulateButton&quot;)</value>
      <webElementGuid>8978ed32-53b3-43cd-8ac6-4c6ecee82d5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='SimulateButton']</value>
      <webElementGuid>f02e40c5-f755-48a0-8d51-c342e0272cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div/form/button</value>
      <webElementGuid>4365268b-a6d1-483a-9ca9-afa03ec3e4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return Time'])[1]/following::button[1]</value>
      <webElementGuid>34c8931f-d158-43f6-945e-d972b0998c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return Date'])[1]/following::button[1]</value>
      <webElementGuid>e6534a3e-145f-4333-a46e-6087523261de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Let', &quot;'&quot;, 's Go')])[1]/preceding::button[1]</value>
      <webElementGuid>c8c2d8a3-7f95-43c5-9123-00834f1f0946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Together!'])[1]/preceding::button[1]</value>
      <webElementGuid>d74a2cb0-5ab0-4ead-be35-5958212d98aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>63fde8ae-6ad0-4252-881e-9cbea4f64e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'SimulateButton' and @type = 'submit' and (text() = 'Find A Car' or . = 'Find A Car')]</value>
      <webElementGuid>cec97723-64cc-423f-b303-d22f368a017b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
