<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Pick-up Location_select__input-container css-15ol6m4</name>
   <tag></tag>
   <elementGuidId>8431e839-8977-4515-ab9a-78f3c510ffa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.select__input-container.css-15ol6m4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/div/form/div/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dce02617-348a-45c7-8d55-c5ec22c27b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select__input-container css-15ol6m4</value>
      <webElementGuid>e0e43272-1819-4fd2-8e7c-d9fdbc300d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;w-screen h-auto&quot;]/section[@class=&quot;w-screen xxs:h-auto xs:h-auto sm:h-auto md:h-screen lg:h-screen xl:h-screen xxl:h-screen bg-hero-home bg-fixed bg-cover flex justify-items-start items-center&quot;]/div[@class=&quot;w-full h-fit mt-10 flex xxs:flex-col-reverse xs:flex-col-reverse sm:flex-col-reverse md:flex-col-reverse lg:flex-row xl:flex-row 2xl:flex-row justify-around items-center xxs:mt-[250px] xs:mt-[250px] sm:mt-[300px] md:mt-[300px]&quot;]/form[@class=&quot;my-5 p-5 bg-white shadow-sm rounded-lg xxs:w-full xxs:min-w-[350px] xxs:max-w-[400px] xs:min-w-[400px] xs:w-full xs:max-w-[500px] sm:min-w-[500px] sm:w-full sm:max-w-[450px] md:w-[450px] lg:w-[500px] xl:w-[500px] xxl:min-w-[500px] self-center transition duration-150 ease-out dark:bg-dSurface xxs:mt-[300px] xs:mt-[300px] sm:mt-[300px] md:mt-[300px] lg:mt-0 xl:mt-0 2xl:mt-0&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;border bg-bgWhite dark:bg-dOnSurfaceBg dark:border-0 css-1jydm44-container&quot;]/div[@class=&quot;select__control css-1gxvstv-control&quot;]/div[@class=&quot;select__value-container css-hlgwow&quot;]/div[@class=&quot;select__input-container css-15ol6m4&quot;]</value>
      <webElementGuid>93d7d802-bd94-4c6b-91e3-a59270adb6ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div/form/div/div/div/div/div[2]</value>
      <webElementGuid>7dfd0dc9-1952-42f5-b02a-9c672d1f2816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Pick-up Location'])[1]/following::div[1]</value>
      <webElementGuid>f2471274-bf66-49bd-8ef0-8b4ab5738f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick-up Location'])[1]/following::div[5]</value>
      <webElementGuid>5591c057-e73f-4f2b-8a6a-cdb027d646a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return to a different location'])[1]/preceding::div[3]</value>
      <webElementGuid>c7828674-c3fc-4672-bce9-448b5a4e1ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help me find a location'])[1]/preceding::div[3]</value>
      <webElementGuid>379e8bf1-13b1-4c80-8c2e-18e5027502ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div[2]</value>
      <webElementGuid>3e21cb77-0e9f-46fc-b73e-cc6d06922018</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
