<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bagan Airport , Bagan</name>
   <tag></tag>
   <elementGuidId>70f2d972-6b80-451a-85ab-90f5d3e57f8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-pickup_location-option-0-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-pickup_location-option-0-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>447054bd-b7ae-4356-b7b6-5da898cc7ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select__option select__option--is-focused css-18bb484-option</value>
      <webElementGuid>1d6c79b7-f7b3-4596-b0c1-cdb2bf431254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>de345a15-cb37-4c64-b10d-a94b26462987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-pickup_location-option-0-0</value>
      <webElementGuid>a0f18d9e-ca32-4d80-9aea-3dcbdd1bc203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8679a8ad-8aa4-4578-ae94-97db8a078914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bagan Airport , Bagan</value>
      <webElementGuid>7028ba9b-3ac9-407b-8dbd-1e617ddfa914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-pickup_location-option-0-0&quot;)</value>
      <webElementGuid>10eaedc0-c862-4cb5-94cc-b8e606246b04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-pickup_location-option-0-0']</value>
      <webElementGuid>32ceb402-ba2f-44e5-9cd8-875e27dfa95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-pickup_location-listbox']/div/div/div[2]/div</value>
      <webElementGuid>00813cdb-6baa-4fd5-b431-4a1681d35482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagan'])[1]/following::div[2]</value>
      <webElementGuid>cf374449-f712-4073-a84e-ee89f85e8432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Pick-up Location'])[1]/following::div[9]</value>
      <webElementGuid>4447e011-64da-4cb6-b5a7-9d532d9ccc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mandalay'])[1]/preceding::div[1]</value>
      <webElementGuid>67249f86-8e3a-4d7d-8eb6-993378e5855d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hilton Mandalay , Aye Thar Zan Township'])[1]/preceding::div[2]</value>
      <webElementGuid>1922bc89-a4b2-49a2-80da-57c5bd4d5a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bagan Airport , Bagan']/parent::*</value>
      <webElementGuid>71def615-4037-43fd-8d4a-7306a2e0fa34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>07894ca0-2503-4505-909e-3bb612c336fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-pickup_location-option-0-0' and (text() = 'Bagan Airport , Bagan' or . = 'Bagan Airport , Bagan')]</value>
      <webElementGuid>b6e41838-6c62-4eed-9ae7-b951e5f0346a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
