<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Return Time_return_time</name>
   <tag></tag>
   <elementGuidId>1212bd43-5c7e-4f45-b976-127eb1ea0a8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;return_time&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='return_time']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87681cc5-53a1-4e03-b97b-af83442defe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>return_time</value>
      <webElementGuid>94ccfdbb-1e14-483e-add0-a1627c1b995a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input bg-bgWhite border border-gray-200 text-gray-900 text-sm placeholder:text-slate-400 rounded-xl focus:outline-none focus:border-primary dark:focus:border-secondary block w-full px-2 rounded-pill form-control dark:bg-dOnSurfaceBg dark:border-0 dark:text-dOnSurface dark:placeholder:text-textWhite flatpickr-input</value>
      <webElementGuid>fb7bce9b-abef-4eea-86dd-9662bbc10a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Return Time</value>
      <webElementGuid>f7d912f6-2693-48b1-9733-c6e731978bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32600004-0b48-4516-8fe2-5ea17855c1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>7dfcf334-1e39-46df-ab47-148cb7d0729a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;w-screen h-auto&quot;]/section[@class=&quot;w-screen xxs:h-auto xs:h-auto sm:h-auto md:h-screen lg:h-screen xl:h-screen xxl:h-screen bg-hero-home bg-fixed bg-cover flex justify-items-start items-center&quot;]/div[@class=&quot;w-full h-fit mt-10 flex xxs:flex-col-reverse xs:flex-col-reverse sm:flex-col-reverse md:flex-col-reverse lg:flex-row xl:flex-row 2xl:flex-row justify-around items-center xxs:mt-[250px] xs:mt-[250px] sm:mt-[300px] md:mt-[300px]&quot;]/form[@class=&quot;my-5 p-5 bg-white shadow-sm rounded-lg xxs:w-full xxs:min-w-[350px] xxs:max-w-[400px] xs:min-w-[400px] xs:w-full xs:max-w-[500px] sm:min-w-[500px] sm:w-full sm:max-w-[450px] md:w-[450px] lg:w-[500px] xl:w-[500px] xxl:min-w-[500px] self-center transition duration-150 ease-out dark:bg-dSurface xxs:mt-[300px] xs:mt-[300px] sm:mt-[300px] md:mt-[300px] lg:mt-0 xl:mt-0 2xl:mt-0&quot;]/div[@class=&quot;grid grid-flow-row gap-2 xs:grid-rows-1 sm:grid-rows-1 md:grid-rows-1 lg:grid-rows-1 xxl:grid-rows-1 xs:grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xxl:grid-cols-2&quot;]/div[@class=&quot;mb-3&quot;]/input[@class=&quot;form-input bg-bgWhite border border-gray-200 text-gray-900 text-sm placeholder:text-slate-400 rounded-xl focus:outline-none focus:border-primary dark:focus:border-secondary block w-full px-2 rounded-pill form-control dark:bg-dOnSurfaceBg dark:border-0 dark:text-dOnSurface dark:placeholder:text-textWhite flatpickr-input&quot;]</value>
      <webElementGuid>3050b857-dd7c-4834-8871-33d9da0848a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='return_time']</value>
      <webElementGuid>58ba4a5c-0899-4b18-8296-32e209580599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div/form/div[4]/div[2]/input</value>
      <webElementGuid>86e91fbb-a86c-4577-9a83-1cd53ea2952b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>dc9e192c-f7d5-4b18-8935-f2483e5d0954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'return_time' and @placeholder = 'Select Return Time' and @type = 'text']</value>
      <webElementGuid>4c45e192-5a98-4b2b-ad0a-4560d1903d37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
