<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pick-up Time_pickup_time</name>
   <tag></tag>
   <elementGuidId>21f27c4a-93cb-4880-afca-d6faf19b8166</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pickup_time&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pickup_time']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8453ecd5-5d80-480d-b5df-f656b3496964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pickup_time</value>
      <webElementGuid>60372e07-a783-4da1-a8ae-48d02237d750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input bg-bgWhite border border-gray-200 text-gray-900 text-sm placeholder:text-slate-400 rounded-xl focus:outline-none focus:border-primary dark:focus:border-secondary block w-full px-2 rounded-pill form-control dark:bg-dOnSurfaceBg dark:border-0 dark:text-dOnSurface dark:placeholder:text-textWhite flatpickr-input</value>
      <webElementGuid>6e6f70e1-c3bb-4eb9-876c-5bef5e44bf57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Pick-up Time</value>
      <webElementGuid>d632fb75-522f-4159-8620-d69bb66f3d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>afa8bba6-b9c3-49a5-b434-35b21328ac77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>43c69552-777f-4b9f-a931-5d09d5c7b844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;w-screen h-auto&quot;]/section[@class=&quot;w-screen xxs:h-auto xs:h-auto sm:h-auto md:h-screen lg:h-screen xl:h-screen xxl:h-screen bg-hero-home bg-fixed bg-cover flex justify-items-start items-center&quot;]/div[@class=&quot;w-full h-fit mt-10 flex xxs:flex-col-reverse xs:flex-col-reverse sm:flex-col-reverse md:flex-col-reverse lg:flex-row xl:flex-row 2xl:flex-row justify-around items-center xxs:mt-[250px] xs:mt-[250px] sm:mt-[300px] md:mt-[300px]&quot;]/form[@class=&quot;my-5 p-5 bg-white shadow-sm rounded-lg xxs:w-full xxs:min-w-[350px] xxs:max-w-[400px] xs:min-w-[400px] xs:w-full xs:max-w-[500px] sm:min-w-[500px] sm:w-full sm:max-w-[450px] md:w-[450px] lg:w-[500px] xl:w-[500px] xxl:min-w-[500px] self-center transition duration-150 ease-out dark:bg-dSurface xxs:mt-[300px] xs:mt-[300px] sm:mt-[300px] md:mt-[300px] lg:mt-0 xl:mt-0 2xl:mt-0&quot;]/div[@class=&quot;grid grid-flow-row gap-2 xs:grid-rows-1 sm:grid-rows-1 md:grid-rows-1 lg:grid-rows-1 xxl:grid-rows-1 xs:grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xxl:grid-cols-2&quot;]/div[@class=&quot;mb-3&quot;]/input[@class=&quot;form-input bg-bgWhite border border-gray-200 text-gray-900 text-sm placeholder:text-slate-400 rounded-xl focus:outline-none focus:border-primary dark:focus:border-secondary block w-full px-2 rounded-pill form-control dark:bg-dOnSurfaceBg dark:border-0 dark:text-dOnSurface dark:placeholder:text-textWhite flatpickr-input&quot;]</value>
      <webElementGuid>8a3d6b80-f6af-4d91-8e60-4492d48cee0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pickup_time']</value>
      <webElementGuid>ba393b33-89c1-4f69-9879-516c1cdeea2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div/form/div[3]/div[2]/input</value>
      <webElementGuid>201eff1e-fc0e-4cb3-bde0-2d1fee96e7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>d673d676-756e-4d08-accb-da7c01a46916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'pickup_time' and @placeholder = 'Select Pick-up Time' and @type = 'text']</value>
      <webElementGuid>b2bb16d1-9825-4a78-b9b9-051022c310c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
