<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__numInput flatpickr-minute</name>
   <tag></tag>
   <elementGuidId>55f177f7-6b26-40bb-a3b9-d5e4b11f0c42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.numInput.flatpickr-minute</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='number'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9eb1e4f-f87e-416b-8921-e3f4c5c5a186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>numInput flatpickr-minute</value>
      <webElementGuid>f9b20f34-fc72-4cc9-9811-4fb4b5634961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c42c0051-f0d1-4208-b126-317a7a984a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Minute</value>
      <webElementGuid>0b46925a-acdd-4e18-9c96-7c3b344764fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>aaccb448-883d-4586-bdb2-551219f02645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>725a022d-a218-4129-a702-c03cdab2155f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1f59482c-bf22-4672-b269-7d21400a8d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>59</value>
      <webElementGuid>a4661fc5-2342-46be-8eeb-5776fcb385cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e29b3af7-70cd-4d2d-99bf-5f8208e36df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;light&quot;]/body[@class=&quot;dark:bg-dBg&quot;]/div[@class=&quot;flatpickr-calendar hasTime noCalendar animate open arrowTop arrowLeft&quot;]/div[@class=&quot;flatpickr-time&quot;]/div[@class=&quot;numInputWrapper&quot;]/input[@class=&quot;numInput flatpickr-minute&quot;]</value>
      <webElementGuid>be90dd3e-c658-4aff-a064-e1a5c0bd78f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='number'])[3]</value>
      <webElementGuid>8bf0020f-309d-49ed-b3b3-9fb46c18bb8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>b3bf14e2-1a40-4a87-a5c2-be0677746a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>1b4fa121-ddf8-4197-a255-21c01338a70c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
