<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Return Date_return_date</name>
   <tag></tag>
   <elementGuidId>04aab3ed-9ab6-4516-950e-1705e07b0c0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;return_date&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='return_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7bac7b5e-8dfc-4933-abb0-68ff4af2b958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>return_date</value>
      <webElementGuid>188b1fa8-ba1f-4f4b-be9d-662ddb1acf05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input bg-bgWhite border border-gray-200 text-gray-900 text-sm placeholder:text-slate-400 rounded-xl focus:outline-none focus:border-primary dark:focus:border-secondary block w-full px-2 rounded-pill form-control dark:bg-dOnSurfaceBg dark:border-0 dark:text-dOnSurface dark:placeholder:text-textWhite flatpickr-input</value>
      <webElementGuid>621279b1-1965-4e05-96a5-d96811f33a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Return Date</value>
      <webElementGuid>c78c2bbe-9b97-448b-9e9f-ad75dc0000b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b755040-6586-4427-bf19-47985acea745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>575d6082-b216-466a-a424-1ce41c4bd10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;w-screen h-auto&quot;]/section[@class=&quot;w-screen xxs:h-auto xs:h-auto sm:h-auto md:h-screen lg:h-screen xl:h-screen xxl:h-screen bg-hero-home bg-fixed bg-cover flex justify-items-start items-center&quot;]/div[@class=&quot;w-full h-fit mt-10 flex xxs:flex-col-reverse xs:flex-col-reverse sm:flex-col-reverse md:flex-col-reverse lg:flex-row xl:flex-row 2xl:flex-row justify-around items-center xxs:mt-[250px] xs:mt-[250px] sm:mt-[300px] md:mt-[300px]&quot;]/form[@class=&quot;my-5 p-5 bg-white shadow-sm rounded-lg xxs:w-full xxs:min-w-[350px] xxs:max-w-[400px] xs:min-w-[400px] xs:w-full xs:max-w-[500px] sm:min-w-[500px] sm:w-full sm:max-w-[450px] md:w-[450px] lg:w-[500px] xl:w-[500px] xxl:min-w-[500px] self-center transition duration-150 ease-out dark:bg-dSurface xxs:mt-[300px] xs:mt-[300px] sm:mt-[300px] md:mt-[300px] lg:mt-0 xl:mt-0 2xl:mt-0&quot;]/div[@class=&quot;grid grid-flow-row gap-2 xs:grid-rows-1 sm:grid-rows-1 md:grid-rows-1 lg:grid-rows-1 xxl:grid-rows-1 xs:grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xxl:grid-cols-2&quot;]/div[@class=&quot;mb-3&quot;]/input[@class=&quot;form-input bg-bgWhite border border-gray-200 text-gray-900 text-sm placeholder:text-slate-400 rounded-xl focus:outline-none focus:border-primary dark:focus:border-secondary block w-full px-2 rounded-pill form-control dark:bg-dOnSurfaceBg dark:border-0 dark:text-dOnSurface dark:placeholder:text-textWhite flatpickr-input&quot;]</value>
      <webElementGuid>f136c3db-bc7b-45b9-9841-0426a98175b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='return_date']</value>
      <webElementGuid>9aa251c5-d92a-4028-96b9-6825b60a56cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div/form/div[4]/div/input</value>
      <webElementGuid>19dd851e-3219-4b49-a803-96a96a162ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>d0f75f66-2cb6-43a0-98b9-6065cfb479c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'return_date' and @placeholder = 'Select Return Date' and @type = 'text']</value>
      <webElementGuid>c050c7aa-7483-453f-a01f-6c5c01e49fd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
