<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pick-up Date_pickup_date</name>
   <tag></tag>
   <elementGuidId>796a9d3b-f415-42eb-823b-6fa1b527a435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pickup_date&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;__next&quot;)/main[@class=&quot;w-screen h-auto&quot;]/section[@class=&quot;w-screen xxs:h-auto xs:h-auto sm:h-auto md:h-screen lg:h-screen xl:h-screen xxl:h-screen bg-hero-home bg-fixed bg-cover flex justify-items-start items-center&quot;]/div[@class=&quot;w-full h-fit mt-10 flex xxs:flex-col-reverse xs:flex-col-reverse sm:flex-col-reverse md:flex-col-reverse lg:flex-row xl:flex-row 2xl:flex-row justify-around items-center xxs:mt-[250px] xs:mt-[250px] sm:mt-[300px] md:mt-[300px]&quot;]/form[@class=&quot;my-5 p-5 bg-white shadow-sm rounded-lg xxs:w-full xxs:min-w-[350px] xxs:max-w-[400px] xs:min-w-[400px] xs:w-full xs:max-w-[500px] sm:min-w-[500px] sm:w-full sm:max-w-[450px] md:w-[450px] lg:w-[500px] xl:w-[500px] xxl:min-w-[500px] self-center transition duration-150 ease-out dark:bg-dSurface xxs:mt-[300px] xs:mt-[300px] sm:mt-[300px] md:mt-[300px] lg:mt-0 xl:mt-0 2xl:mt-0&quot;]/div[@class=&quot;grid grid-flow-row gap-2 xs:grid-rows-1 sm:grid-rows-1 md:grid-rows-1 lg:grid-rows-1 xxl:grid-rows-1 xs:grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xxl:grid-cols-2&quot;]/div[@class=&quot;mb-3&quot;]/input[@class=&quot;form-input bg-bgWhite border border-gray-200 text-gray-900 text-sm placeholder:text-slate-400 rounded-xl focus:outline-none focus:border-primary dark:focus:border-secondary block w-full px-2 rounded-pill form-control dark:bg-dOnSurfaceBg dark:border-0 dark:text-dOnSurface dark:placeholder:text-textWhite flatpickr-input&quot;][count(. | //input[@name = 'pickup_date' and @class = 'form-input bg-bgWhite border border-gray-200 text-gray-900 text-sm placeholder:text-slate-400 rounded-xl focus:outline-none focus:border-primary dark:focus:border-secondary block w-full px-2 rounded-pill form-control dark:bg-dOnSurfaceBg dark:border-0 dark:text-dOnSurface dark:placeholder:text-textWhite flatpickr-input' and @placeholder = 'Select Pick-up Date' and @type = 'text' and @readonly = 'readonly']) = count(//input[@name = 'pickup_date' and @class = 'form-input bg-bgWhite border border-gray-200 text-gray-900 text-sm placeholder:text-slate-400 rounded-xl focus:outline-none focus:border-primary dark:focus:border-secondary block w-full px-2 rounded-pill form-control dark:bg-dOnSurfaceBg dark:border-0 dark:text-dOnSurface dark:placeholder:text-textWhite flatpickr-input' and @placeholder = 'Select Pick-up Date' and @type = 'text' and @readonly = 'readonly'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pickup_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f50715c3-4b57-4bea-99f6-f04835dfb2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pickup_date</value>
      <webElementGuid>2923da9f-0eb6-44b2-8d48-9c3bbe9ef644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input bg-bgWhite border border-gray-200 text-gray-900 text-sm placeholder:text-slate-400 rounded-xl focus:outline-none focus:border-primary dark:focus:border-secondary block w-full px-2 rounded-pill form-control dark:bg-dOnSurfaceBg dark:border-0 dark:text-dOnSurface dark:placeholder:text-textWhite flatpickr-input</value>
      <webElementGuid>98952145-a3f2-4026-8faa-b0e74cfe28e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Pick-up Date</value>
      <webElementGuid>f86dee1d-546d-4aaa-858d-a9eef02e5768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e7deb08-cffe-4ec2-abf1-ee2c08d19812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>e0f7e35d-28ce-4431-b4fa-b508287f2560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;w-screen h-auto&quot;]/section[@class=&quot;w-screen xxs:h-auto xs:h-auto sm:h-auto md:h-screen lg:h-screen xl:h-screen xxl:h-screen bg-hero-home bg-fixed bg-cover flex justify-items-start items-center&quot;]/div[@class=&quot;w-full h-fit mt-10 flex xxs:flex-col-reverse xs:flex-col-reverse sm:flex-col-reverse md:flex-col-reverse lg:flex-row xl:flex-row 2xl:flex-row justify-around items-center xxs:mt-[250px] xs:mt-[250px] sm:mt-[300px] md:mt-[300px]&quot;]/form[@class=&quot;my-5 p-5 bg-white shadow-sm rounded-lg xxs:w-full xxs:min-w-[350px] xxs:max-w-[400px] xs:min-w-[400px] xs:w-full xs:max-w-[500px] sm:min-w-[500px] sm:w-full sm:max-w-[450px] md:w-[450px] lg:w-[500px] xl:w-[500px] xxl:min-w-[500px] self-center transition duration-150 ease-out dark:bg-dSurface xxs:mt-[300px] xs:mt-[300px] sm:mt-[300px] md:mt-[300px] lg:mt-0 xl:mt-0 2xl:mt-0&quot;]/div[@class=&quot;grid grid-flow-row gap-2 xs:grid-rows-1 sm:grid-rows-1 md:grid-rows-1 lg:grid-rows-1 xxl:grid-rows-1 xs:grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xxl:grid-cols-2&quot;]/div[@class=&quot;mb-3&quot;]/input[@class=&quot;form-input bg-bgWhite border border-gray-200 text-gray-900 text-sm placeholder:text-slate-400 rounded-xl focus:outline-none focus:border-primary dark:focus:border-secondary block w-full px-2 rounded-pill form-control dark:bg-dOnSurfaceBg dark:border-0 dark:text-dOnSurface dark:placeholder:text-textWhite flatpickr-input&quot;]</value>
      <webElementGuid>221ea16c-b823-4439-8b96-a186244d4006</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pickup_date']</value>
      <webElementGuid>c9e1c368-3434-4fb3-97f1-05aaa3619dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div/form/div[3]/div/input</value>
      <webElementGuid>ba96244b-7486-417c-b389-e0960e4c47b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>65cd91d9-b8ee-4eb3-b8d8-56d432284e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'pickup_date' and @placeholder = 'Select Pick-up Date' and @type = 'text']</value>
      <webElementGuid>279e7b91-4d68-457f-9f0a-263cdec5c3a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
