<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Find A Car</name>
   <tag></tag>
   <elementGuidId>dd048423-31a8-4ced-90e0-b4da0a6421c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/nav/div/div/div/div[2]/div/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>284429bb-ece7-4f8f-b6b2-ca230c53912f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d47951a1-7a59-4a56-8159-eafd7f678dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-textBlack hover:text-primary p-2 rounded-md text-sm font-medium font-source-serif uppercase dark:text-dOnSurface dark:hover:text-secondary </value>
      <webElementGuid>0fae5191-5cef-4e59-af1b-7b07d4e8a098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find A Car</value>
      <webElementGuid>0b8648db-7476-4333-86f3-223307cf73bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/nav[@class=&quot;fixed top-0 z-50&quot;]/div[@class=&quot;w-screen&quot;]/div[@class=&quot;primaryHeader flex items-center justify-between h-20 p-3 px-5 bg-white rounded-lg shadow-lg border m-3 dark:bg-dSurface dark:shadow-sm dark:border-0&quot;]/div[@class=&quot;flex items-center flex-1&quot;]/div[@class=&quot;hidden lg:block xl:block xxl:block&quot;]/div[@class=&quot;ml-10 flex items-center&quot;]/a[@class=&quot;text-textBlack hover:text-primary p-2 rounded-md text-sm font-medium font-source-serif uppercase dark:text-dOnSurface dark:hover:text-secondary&quot;]</value>
      <webElementGuid>14f4cb1c-7ee4-4894-9962-ca84f4eaebb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/nav/div/div/div/div[2]/div/a[3]</value>
      <webElementGuid>1ac23ee7-8ac3-4c01-983a-61e13c54bd88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Find A Car')]</value>
      <webElementGuid>3223def2-e8b8-4eca-a3ae-46b68523371d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open user menu'])[1]/preceding::a[2]</value>
      <webElementGuid>b9941335-ad6e-46da-a5c8-60cba6479347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/preceding::a[2]</value>
      <webElementGuid>9dbeb234-8594-4acc-899e-3ea808207733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Find A Car']/parent::*</value>
      <webElementGuid>975f39ab-5ecd-4c0b-80e7-7e75b89f08ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>fa75a707-62fc-4e3b-905b-4d2426913ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>d4d3b6cd-efde-454a-be94-3d81b859837a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Find A Car' or . = 'Find A Car')]</value>
      <webElementGuid>71b2e0de-412d-4cd0-9640-a94f5330917d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
