<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Locations</name>
   <tag></tag>
   <elementGuidId>3c111664-9141-4eb8-ad53-a72a3f46e011</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/nav/div/div/div/div[2]/div/a[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d13a35fe-49da-4362-8b3c-d9728b537b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>35003de8-2201-4aab-a8f2-1a1e92649288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-textBlack hover:text-primary p-2 rounded-md text-sm font-medium font-source-serif uppercase dark:text-dOnSurface dark:hover:text-secondary </value>
      <webElementGuid>2c35d0cb-99f1-4f07-a817-12c7c666d1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Locations</value>
      <webElementGuid>cb230e74-aa4e-4208-b6f6-3e9c1c3b6737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/nav[@class=&quot;fixed top-0 z-50&quot;]/div[@class=&quot;w-screen&quot;]/div[@class=&quot;primaryHeader flex items-center justify-between h-20 p-3 px-5 bg-white rounded-lg shadow-lg border m-3 dark:bg-dSurface dark:shadow-sm dark:border-0&quot;]/div[@class=&quot;flex items-center flex-1&quot;]/div[@class=&quot;hidden lg:block xl:block xxl:block&quot;]/div[@class=&quot;ml-10 flex items-center&quot;]/a[@class=&quot;text-textBlack hover:text-primary p-2 rounded-md text-sm font-medium font-source-serif uppercase dark:text-dOnSurface dark:hover:text-secondary&quot;]</value>
      <webElementGuid>4813f484-2c29-4df0-b8cf-b7cce5f1e4c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/nav/div/div/div/div[2]/div/a[4]</value>
      <webElementGuid>c4059b02-129b-444e-a439-30ede45034ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Locations')]</value>
      <webElementGuid>b3fdba05-70cf-475e-b111-691ea603c928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open user menu'])[1]/preceding::a[1]</value>
      <webElementGuid>af65635e-c116-4ba5-bdf0-a1a3f3d88308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/preceding::a[1]</value>
      <webElementGuid>34731159-27c9-4a60-b86b-3e62bd0491a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Locations']/parent::*</value>
      <webElementGuid>9828a0c1-59e5-4ad8-9d68-a4ec24243c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>7681ff2d-b338-4124-b428-eb8a96213f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>dfdf3b37-f533-4d85-bf73-4c1cf462e008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Locations' or . = 'Locations')]</value>
      <webElementGuid>49d7cfc4-eb20-4435-81da-1a46e3a0d450</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
