<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__numInput flatpickr-minute</name>
   <tag></tag>
   <elementGuidId>bea3de54-69a0-4648-9588-8f1c8c7c7d0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flatpickr-calendar.hasTime.noCalendar.animate.open.arrowTop.arrowLeft > div.flatpickr-time > div.numInputWrapper > input.numInput.flatpickr-minute</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='number'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7fbc949-d1ce-48f8-a95b-2b332e5eaba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>numInput flatpickr-minute</value>
      <webElementGuid>d8f1d1d7-b64b-4b78-acac-68d422242e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9fdd9223-5ef3-4102-8961-de1a235e1654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Minute</value>
      <webElementGuid>8e804f54-d60e-427b-a6fd-b6edb2929ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>665a2def-0244-43c5-904e-19fbcf9bb10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>499a1c31-860b-4cee-8f48-c2e036111f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a1172dd6-f47b-4ac2-b981-05e80113bbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>59</value>
      <webElementGuid>a9cae8c7-4494-43d2-8f4e-6e4b763c4321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>17c42cf4-6371-42fd-9619-3a09d1c855ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;light&quot;]/body[@class=&quot;dark:bg-dBg&quot;]/div[@class=&quot;flatpickr-calendar hasTime noCalendar animate open arrowTop arrowLeft&quot;]/div[@class=&quot;flatpickr-time&quot;]/div[@class=&quot;numInputWrapper&quot;]/input[@class=&quot;numInput flatpickr-minute&quot;]</value>
      <webElementGuid>5b438387-d80c-4970-afd7-93fa0eecb579</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='number'])[6]</value>
      <webElementGuid>aa952175-4856-433d-aff8-d4711a5f225b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>b67aa41e-9875-41d9-afcc-773f88de2913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>0bafcc9b-3ef0-4a8d-9726-c6d2c5b853ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
