<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sat_numInput flatpickr-hour</name>
   <tag></tag>
   <elementGuidId>882c90cb-c2f8-4b31-89cf-533840273e74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flatpickr-calendar.hasTime.noCalendar.animate.open.arrowTop.arrowLeft > div.flatpickr-time > div.numInputWrapper > input.numInput.flatpickr-hour</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='number'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5472624f-5bea-41ec-b2af-f8dca1300078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>numInput flatpickr-hour</value>
      <webElementGuid>ce47d813-2d4d-44ed-8eb1-6b595bdf12e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e3f20e9a-2c49-4a65-958e-f4303087b6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Hour</value>
      <webElementGuid>cc465922-27bd-45e1-84c0-e5ce23a78a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>e298b7de-8c16-4fab-a22f-b72d7ecf75bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8bb9c91d-5f34-4e7c-a636-56282be5cf7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f1015105-a311-4fe2-b624-b37c9bf6ec5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>8509a866-4d16-46a2-9b37-a3a74bb1a8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>040d3278-83c7-48fb-8311-e041b0850fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;light&quot;]/body[@class=&quot;dark:bg-dBg&quot;]/div[@class=&quot;flatpickr-calendar hasTime noCalendar animate open arrowTop arrowLeft&quot;]/div[@class=&quot;flatpickr-time&quot;]/div[@class=&quot;numInputWrapper&quot;]/input[@class=&quot;numInput flatpickr-hour&quot;]</value>
      <webElementGuid>3d8a14b6-0efb-4af6-b161-21797fc3a4cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='number'])[5]</value>
      <webElementGuid>059279b2-251a-46cb-9457-b5dbaf40a69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>6dae9215-b432-4648-8a98-11fd53f21c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>2e75d384-523d-437c-a1f3-198305387384</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
