<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hilton Mandalay , Aye Thar Zan Township</name>
   <tag></tag>
   <elementGuidId>d6ca0f09-7a6c-43ac-8605-a78d50f2cc3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-pickup_location-option-1-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-pickup_location-option-1-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7c06e4bd-5bd6-4be4-83c9-d1f48d34ca14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select__option select__option--is-focused css-18bb484-option</value>
      <webElementGuid>85365fe8-29e0-4161-9040-7fd8f9754b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>255d49d1-7350-4025-821e-386167626c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-pickup_location-option-1-0</value>
      <webElementGuid>b34904e3-73ff-4bac-9093-51e2bd2d9097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1a104e90-56dd-404e-ab03-26e270f54e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hilton Mandalay , Aye Thar Zan Township</value>
      <webElementGuid>c85f8c0d-7f6d-4da9-8578-27a1755a1d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-pickup_location-option-1-0&quot;)</value>
      <webElementGuid>cae03520-d0db-4366-9c9f-ab169913ffd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-pickup_location-option-1-0']</value>
      <webElementGuid>5139671a-6924-4e3f-92bf-22d4e81a5d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-pickup_location-listbox']/div/div[2]/div[2]/div</value>
      <webElementGuid>5c3b4ed4-9dd0-44b2-9602-b4977d887fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mandalay'])[1]/following::div[2]</value>
      <webElementGuid>43a9d0fa-2ca4-4d9f-8ba8-babc6d31d4b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagan Airport , Bagan'])[1]/following::div[4]</value>
      <webElementGuid>e612e392-e7c4-4771-933f-28c892df463c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mandalay Airport , Mandalay'])[1]/preceding::div[1]</value>
      <webElementGuid>dc4ec7e7-e587-4917-a3d6-fc66a4b43bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mandalay City (Chan Mya Thar Si) , Chan Mya Thar Si Township'])[1]/preceding::div[2]</value>
      <webElementGuid>d4c466b9-ba21-4f72-a78f-efd541d6055d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hilton Mandalay , Aye Thar Zan Township']/parent::*</value>
      <webElementGuid>5b42e514-1d01-4178-8500-bef919d5e13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/div</value>
      <webElementGuid>755d0896-ce2a-4238-8a7f-1c39d2c5d0c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-pickup_location-option-1-0' and (text() = 'Hilton Mandalay , Aye Thar Zan Township' or . = 'Hilton Mandalay , Aye Thar Zan Township')]</value>
      <webElementGuid>79e3c2b9-7f56-4e9e-a3e8-49abfc7efbf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
